#+TITLE: Orviz - An interactive visualizer and explorer for your Org-Roam notes
** Installation
   Currently the installation procedure is long and complicated, and is provided only for beta testing purposes. In future releases we will reasonably simplify it - so that it becomes just one script.

   There are several components to the installation procedure, read the following guide carefully, and feel free to get in touch if something is confusing.

*** Requirements

**** node and npm
**** http-server
**** (of course) updated installation of Emacs with org-roam

*** Note Browser Setup
    For Orviz's note browser to work it needs to have the entire org directory published as HTML files, we will use org's native publishing feature for this.
    Add the following to your Emacs init file.
    #+begin_src elisp

      (defun orviz/org-roam--backlinks-list-with-content (file)
        (with-temp-buffer
          (if-let* ((backlinks (org-roam--get-backlinks file))
                    (grouped-backlinks (--group-by (nth 0 it) backlinks)))
              (progn
                (insert (format "\n\n* %d Backlinks\n"
                                (length backlinks)))
                (dolist (group grouped-backlinks)
                  (let ((file-from (car group))
                        (bls (cdr group)))
                    (insert (format "** [[file:%s][%s]]\n"
                                    file-from
                                    (org-roam--get-title-or-slug file-from)))
                    (dolist (backlink bls)
                      (pcase-let ((`(,file-from _ ,props) backlink))
                        (insert (s-trim (s-replace "\n" " " (plist-get props :content))))
                        (insert "\n\n")))))))
          (buffer-string)))

      (defun orviz/org-export-preprocessor (backend)
        (let ((links (orviz/org-roam--backlinks-list-with-content (buffer-file-name))))
          (unless (string= links "")
            (save-excursion
              (goto-char (point-max))
              (insert links)))))

      (add-hook 'org-export-before-processing-hook 'orviz/org-export-preprocessor)

    #+end_src

    Also add the following in your initfile, after carefully replacing
    - /path/to/your/org-roam-files/directory/
    - /path/to/your/orviz/public/directory/
    #+begin_src elisp

      (setq org-publish-project-alist
            '(("orviz"
               :base-directory "/path/to/your/org-roam-files/directory/"
               :base-extension "org"
               :publishing-directory " /path/to/your/orviz/public/directory/"
               :recursive t
               :publishing-function org-html-publish-to-html
               ;; :headline-levels
               :section-numbers nil
               :with-toc nil
               ;; :include ".*"
               :html-head-extra
               "<link rel=\"stylesheet\" href=\"./static/stylesheet.css\" />"
               :html-postamble nil)))
    #+end_src

*** Orviz setup
    1. Create an ~orviz~ directory somewhere easily accessible in your filesystem.
    2. ~cd~ into it.
    3. ~mkdir -p static public~
